### ISSUE TITLE
Tag initial release

### ISSUE THREAD

**Issue by jaguillette** [Harvard-ATG/ood-remote-desktop#1]
I'm proposing to tag an initial release of this repo off of the main branch. Since there isn't an existing state to compare to, I'm starting the discussion as an issue, rather than a PR. There's a readme that documents how things are set up, and what needs to be in place before running the app, and the app includes specs for the spack environment and apptainer container that it relies on.

**Comment by arthurian** [comment]
@jaguillette I agree, let's tag an initial release off of the `main` branch. I looked at the README as well and that looks to be in good shape. :+1:

**Comment by Tanvez** [comment]
@jaguillette This sounds good to me!

**Comment by jaguillette** [comment]
Tagged! Release is at https://github.com/Harvard-ATG/ood-remote-desktop/releases/tag/v1.0.0
